In [1]:
###########################
# 라이브러리 사용
import pandas as pd
 
###########################
# 파일로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
 
###########################
# 데이터의 모양확인
print(레모네이드.shape)
print(보스턴.shape)
print(아이리스.shape)
 
###########################
# 데이터 칼럼이름 확인
print(레모네이드.columns)
print(보스턴.columns)
print(아이리스.columns)
 
 
###########################
# 독립변수와 종속변수 분리
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)
 
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)
 
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)
 
 
###########################
# 각각의 데이터 확인해보기
print(레모네이드.head())
print(보스턴.head())
print(아이리스.head())

(6, 2)
(506, 14)
(150, 5)
Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')
(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)
   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90 

In [3]:
import tensorflow as tf

In [ ]:
# 회귀와 분류를 나누는 기준은 종속 변수의 데이터 타입
# 종속 변수가 양적 데이터인 경우 회귀
# 종속 변수가 범주형 데이터인 경우 분류

In [7]:
# 회귀 모델

레모네이드_독립 = 레모네이드[['온도']]
레모네이드_종속 = 레모네이드[['판매량']]
print(레모네이드_독립.shape, 레모네이드_종속.shape)

X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

model.fit(레모네이드_독립, 레모네이드_종속, epochs=1000, verbose=0)
model.fit(레모네이드_독립, 레모네이드_종속, epochs=10)

(6, 1) (6, 1)
Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 134.9176
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 134.3805
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 133.8445
Epoch 4/10
1/1 [==============================] - 0s 2ms/step - loss: 133.3096
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 132.7759
Epoch 6/10
1/1 [==============================] - 0s 3ms/step - loss: 132.2432
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 131.7116
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 131.1810
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 130.6516
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 130.1232


In [11]:
model.fit(레모네이드_독립, 레모네이드_종속, epochs=10000, verbose=0)
model.fit(레모네이드_독립, 레모네이드_종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0018
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 5/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0018
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0018
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0018


array([[30.190197]], dtype=float32)

In [12]:
model.predict(레모네이드_독립)
model.predict([15])

array([[30.190197]], dtype=float32)

In [13]:
보스턴_독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
보스턴_종속 = 보스턴[['medv']]
print(보스턴_독립.shape, 보스턴_종속.shape)

(506, 13) (506, 1)


In [14]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [19]:
model.fit(보스턴_독립, 보스턴_종속, epochs=1000, verbose=0)
model.fit(보스턴_독립, 보스턴_종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.6289
Epoch 2/10
16/16 [==============================] - 0s 844us/step - loss: 23.4601
Epoch 3/10
16/16 [==============================] - 0s 690us/step - loss: 23.2962
Epoch 4/10
16/16 [==============================] - 0s 564us/step - loss: 24.1951
Epoch 5/10
16/16 [==============================] - 0s 690us/step - loss: 23.9203
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.7203
Epoch 7/10
16/16 [==============================] - 0s 690us/step - loss: 24.0803
Epoch 8/10
16/16 [==============================] - 0s 564us/step - loss: 23.3775
Epoch 9/10
16/16 [==============================] - 0s 690us/step - loss: 24.0721
Epoch 10/10
16/16 [==============================] - 0s 690us/step - loss: 23.5578


In [24]:
print(model.predict(보스턴_독립[0:5]))
print(보스턴_종속[0:5])

[[29.6256  ]
 [24.542263]
 [30.973005]
 [29.51471 ]
 [29.123993]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [23]:
model.get_weights()

[array([[-0.09753413],
        [ 0.04887441],
        [-0.01571391],
        [ 2.636688  ],
        [-3.979567  ],
        [ 5.1675158 ],
        [-0.00862956],
        [-1.1007258 ],
        [ 0.20841272],
        [-0.01109212],
        [-0.55604434],
        [ 0.01298231],
        [-0.46614277]], dtype=float32),
 array([10.763033], dtype=float32)]

In [31]:
# 범주형 분류 모델
아이리스 = pd.read_csv(파일경로)
아이리스 = pd.get_dummies(아이리스) #원핫인코딩 -> 범주형 데이터 변수들만 전부 원핫인코딩 된 결과로 바꿔줌
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [32]:
아이리스_독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
아이리스_종속 = 아이리스[['품종_setosa','품종_versicolor', '품종_virginica']]
print(아이리스_독립.shape, 아이리스_종속.shape)

(150, 4) (150, 3)


In [44]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X) #Sigmoid, Softmax 차이는??
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [45]:
model.fit(아이리스_독립, 아이리스_종속,  epochs=1000, verbose=0)
model.fit(아이리스_독립, 아이리스_종속,  epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1578 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1574 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1570 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 803us/step - loss: 0.1574 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1567 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1569 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1566 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1563 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1567 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1563 - accuracy: 0.9800


In [48]:
model.predict(아이리스_독립[-5:])

array([[1.5406716e-06, 1.3597828e-01, 8.6402023e-01],
       [2.8470263e-06, 2.3161831e-01, 7.6837879e-01],
       [6.0172188e-06, 2.3764206e-01, 7.6235193e-01],
       [1.6698392e-06, 7.5319849e-02, 9.2467844e-01],
       [1.3757472e-05, 2.3859760e-01, 7.6138860e-01]], dtype=float32)

In [49]:
아이리스_종속[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [51]:
model.get_weights()

[array([[ 1.0781492 ,  1.0698626 , -0.25094453],
        [ 3.0304344 , -0.11168361, -0.946266  ],
        [-3.3051898 , -0.3979685 ,  1.2621813 ],
        [-3.6524105 , -0.9664361 ,  2.192296  ]], dtype=float32),
 array([ 1.6654793,  1.2400923, -1.4555138], dtype=float32)]

# 히든레이어

In [70]:
보스턴_독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
보스턴_종속 = 보스턴[['medv']]
print(보스턴_독립.shape, 보스턴_종속.shape)

(506, 13) (506, 1)


In [71]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
H = tf.keras.layers.Dense(3, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [72]:
model.fit(보스턴_독립, 보스턴_종속, epochs=1000, verbose=0)
model.fit(보스턴_독립, 보스턴_종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 13.8312
Epoch 2/10
16/16 [==============================] - 0s 878us/step - loss: 13.6428
Epoch 3/10
16/16 [==============================] - 0s 815us/step - loss: 13.9941
Epoch 4/10
16/16 [==============================] - 0s 941us/step - loss: 13.1019
Epoch 5/10
16/16 [==============================] - 0s 752us/step - loss: 13.9294
Epoch 6/10
16/16 [==============================] - 0s 752us/step - loss: 13.9575
Epoch 7/10
16/16 [==============================] - 0s 815us/step - loss: 14.3335
Epoch 8/10
16/16 [==============================] - 0s 752us/step - loss: 15.4588
Epoch 9/10
16/16 [==============================] - 0s 878us/step - loss: 13.4294
Epoch 10/10
16/16 [==============================] - 0s 815us/step - loss: 13.9639


In [73]:
#모델 구조 확인
model.summary()

Model: "functional_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_22 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_23 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_24 (Dense)             (None, 3)                 18        
_________________________________________________________________
dense_25 (Dense)             (None, 1)                 4         
Total params: 217
Trainable params: 217
Non-trainable params: 0
_________________________________________________________________


In [76]:
print(model.predict(보스턴_독립[:5]))
print(보스턴_종속[:5])

[[32.206196]
 [26.14944 ]
 [33.730877]
 [32.837086]
 [31.909294]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [84]:
#모델 수식 확인
model.get_weights()

[array([[ 0.03591019, -0.11223198, -0.3453029 ,  0.5950478 , -0.2755047 ,
          0.74850816, -0.3127052 , -0.33373657, -0.01024955,  0.2874885 ],
        [-0.36273286,  0.77487326,  0.41843784,  0.41367158,  0.01253781,
         -0.33213642, -0.28715408,  0.8361188 , -0.23051511, -0.23364155],
        [ 0.7138604 , -0.49930775, -0.337704  , -0.5433954 , -0.19126257,
         -0.34328806, -0.04715502,  0.5904222 , -0.209585  ,  0.5488286 ],
        [ 0.19454071,  0.1487008 , -0.23577961, -0.67338526, -0.14375766,
         -0.9998876 ,  0.23974462,  0.42853686, -0.6264509 ,  0.11268824]],
       dtype=float32),
 array([-0.11939371,  0.43554512,  0.48124787,  0.43209288,  0.45464292,
         0.4027073 ,  0.23608279,  0.0530416 ,  0.38919544, -0.21430694],
       dtype=float32),
 array([[ 0.37428683,  0.9457434 , -0.54128355, -0.7826159 ,  0.599238  ],
        [-0.78681624,  0.42284575,  0.58895063,  0.6041503 , -0.28445446],
        [ 0.41013476,  0.09621978, -1.5162041 , -1.0172613 ,

In [77]:
아이리스 = pd.read_csv(파일경로)
아이리스 = pd.get_dummies(아이리스) #원핫인코딩 -> 범주형 데이터 변수들만 전부 원핫인코딩 된 결과로 바꿔줌
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [80]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
H = tf.keras.layers.Dense(3, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H) #Sigmoid, Softmax 차이는??
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [91]:
아이리스_독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
아이리스_종속 = 아이리스[['품종_setosa','품종_versicolor', '품종_virginica']]
print(아이리스_독립.shape, 아이리스_종속.shape)

(150, 4) (150, 3)


In [92]:
model.fit(아이리스_독립, 아이리스_종속,  epochs=1000, verbose=0)
model.fit(아이리스_독립, 아이리스_종속,  epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0483 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0616 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0453 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0348 - accuracy: 0.9933
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0378 - accuracy: 0.9933
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0453 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0623 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0778 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1043 - accuracy: 0.9600
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0590 - accuracy: 0.9733


In [83]:
print(model.predict(아이리스_독립[:5]))
print(아이리스_종속[:5])

[[9.9999988e-01 3.5038670e-09 1.0268629e-07]
 [9.9999928e-01 4.4586383e-08 6.9424584e-07]
 [9.9999964e-01 1.5774445e-08 3.4352962e-07]
 [9.9999809e-01 1.5928396e-07 1.7368917e-06]
 [9.9999988e-01 3.2511709e-09 9.7598402e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


# 학습이 잘 되는 모델

- 사용할 레이어
 - tf.keras.layers.BatchNormalization()
 - tf.keras.layers.Activation('swish')

In [85]:
보스턴_독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
보스턴_종속 = 보스턴[['medv']]
print(보스턴_독립.shape, 보스턴_종속.shape)

(506, 13) (506, 1)


In [86]:
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(10)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(3)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [87]:
model.fit(보스턴_독립, 보스턴_종속,  epochs=1000, verbose=0)
model.fit(보스턴_독립, 보스턴_종속,  epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 11.2736
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 9.8882
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 10.9521
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 10.9368
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1965
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 12.9903
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 10.2773
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1423
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 11.0906
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 10.6787


In [88]:
아이리스 = pd.read_csv(파일경로)
아이리스 = pd.get_dummies(아이리스) #원핫인코딩 -> 범주형 데이터 변수들만 전부 원핫인코딩 된 결과로 바꿔줌
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [93]:
아이리스_독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
아이리스_종속 = 아이리스[['품종_setosa','품종_versicolor', '품종_virginica']]
print(아이리스_독립.shape, 아이리스_종속.shape)

(150, 4) (150, 3)


In [100]:
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(3)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H) #Sigmoid, Softmax 차이는??
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [101]:
model.fit(아이리스_독립, 아이리스_종속,  epochs=1000, verbose=0)
model.fit(아이리스_독립, 아이리스_종속,  epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0313 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0517 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0447 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0422 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0427 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0524 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0327 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0380 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0350 - accuracy: 0.9867
