In [122]:
import numpy as np  
#1차원
array1 = np.array([1,3,5,7,9,10,11,12])  
print(type(array1), array1, sep='\n')
print("슬라이싱 데이터 추출 [0:3]:", array1[0:3])
print("배열 차원 :", array1.ndim)
print("배열 크기 :", array1.shape)
print("배열 원소 크기 :", array1.itemsize)
print("배열 원소 개수 :", array1.size)
print("배열 내 데이터 타입 :", array1.dtype)
print("데이터 타입 변경 int32 -> float32")
array1 = array1.astype('float32')
print("배열 내 데이터 타입 :", array1.dtype)
print("팬시 인덱싱 [[2,4,6]] :", array1[[2,4,6]])  
print("불린 인덱싱 [원소를 2로 나눈 나머지가 0] :", array1 % 2 == 0) 

<class 'numpy.ndarray'>
[ 1  3  5  7  9 10 11 12]
슬라이싱 데이터 추출 [0:3]: [1 3 5]
배열 차원 : 1
배열 크기 : (8,)
배열 원소 크기 : 4
배열 원소 개수 : 8
배열 내 데이터 타입 : int32
데이터 타입 변경 int32 -> float32
배열 내 데이터 타입 : float32
팬시 인덱싱 [[2,4,6]] : [ 5.  9. 11.]
불린 인덱싱 [원소를 2로 나눈 나머지가 0] : [False False False False False  True False  True]


In [118]:
#2차원
array2 = np.array([[1,3,5,7], [2,4,6,8]])  
print("배열 차원 :", array2.ndim)
print("배열 크기 :", array2.shape)
print("배열 원소 크기 :", array2.itemsize)
print("배열 원소 개수 :", array2.size)
print("배열 내 데이터 타입 :", array2.dtype)
print("데이터 타입 변경 int32 -> float32")
array1 = array2.astype('float32')
print("배열 내 데이터 타입 :", array2.dtype)

print(type(array2), array2, sep='\n')
print("axis0 :", array2.sum(axis=0)) #axis 0 기준으로 더하기  
print("axis1 :", array2.sum(axis=1)) #axis 1 기준으로 더하기  
print("array2 전체 합 : %d" % array2.sum())     #2차원 배열 전체 합

print("슬라이싱 데이터 추출 [0:2, 0:2]:\n", array2[0:2, 0:2])  
print("슬라이싱 데이터 추출 [0:2, :]:\n", array2[0:2, :])  
print("슬라이싱 데이터 추출 [:, 0:1]:\n", array2[:, 0:1])  
print("슬라이싱 데이터 추출 [:, :]:\n", array2[:, :])  
print("슬라이싱 데이터 추출 [:2, 1:]:\n", array2[:2, 1:])  

print("팬시 인덱싱[[0,1],[1,2]]:\n", array2[[0,1],[1,2]])  
print("팬시 인덱싱[[0,1],1:2]:\n", array2[[0,1],1:2])  
print("팬시 인덱싱[[0,1],3]:\n", array2[[0,1],3])  
print("팬시 인덱싱[[0,1]]:\n", array2[[0,1]])  

배열 차원 : 2
배열 크기 : (2, 4)
배열 원소 크기 : 4
배열 원소 개수 : 8
배열 내 데이터 타입 : int32
데이터 타입 변경 int32 -> float32
배열 내 데이터 타입 : int32
<class 'numpy.ndarray'>
[[1 3 5 7]
 [2 4 6 8]]
axis0 : [ 3  7 11 15]
axis1 : [16 20]
array2 전체 합 : 36
슬라이싱 데이터 추출 [0:2, 0:2]:
 [[1 3]
 [2 4]]
슬라이싱 데이터 추출 [0:2, :]:
 [[1 3 5 7]
 [2 4 6 8]]
슬라이싱 데이터 추출 [:, 0:1]:
 [[1]
 [2]]
슬라이싱 데이터 추출 [:, :]:
 [[1 3 5 7]
 [2 4 6 8]]
슬라이싱 데이터 추출 [:2, 1:]:
 [[3 5 7]
 [4 6 8]]
팬시 인덱싱[[0,1],[1,2]]:
 [3 6]
팬시 인덱싱[[0,1],1:2]:
 [[3]
 [4]]
팬시 인덱싱[[0,1],3]:
 [7 8]
팬시 인덱싱[[0,1]]:
 [[1 3 5 7]
 [2 4 6 8]]


In [115]:
#3차원
array3 = np.array([[[1,3,5,7], [2,4,6,8]], [[11,13,15,17], [12,14,16,18]]]) 
print("배열 차원 :", array3.ndim)
print("배열 크기 :", array3.shape)
print("배열 원소 크기 :", array3.itemsize)
print("배열 원소 개수 :", array3.size)
print("배열 내 데이터 타입 :", array3.dtype)
print("데이터 타입 변경 int32 -> float32")
array1 = array3.astype('float32')
print("배열 내 데이터 타입 :", array3.dtype)

print(type(array3), array3, sep='\n')
print("axis0 :", array3.sum(axis=0), sep='\n') #axis 0 기준으로 더하기  
print("axis1 :", array3.sum(axis=1), sep='\n') #axis 1 기준으로 더하기  
print("axis2 :", array3.sum(axis=2), sep='\n') #axis 2 기준으로 더하기  
print("array3 전체 합 : %d" % array3.sum())     #3차원 배열 전체 합

print("슬라이싱 데이터 추출 [0:2, 0:2, 0:2]:\n", array3[0:2, 0:2, 0:2])  
print("슬라이싱 데이터 추출 [0:2, : , 0:2]:\n", array3[0:2, : , 0:2])  
print("슬라이싱 데이터 추출 [:, 0:1, :]:\n", array3[:, 0:1, :])  
print("슬라이싱 데이터 추출 [:, :, :]:\n", array3[:, :, :])  
print("슬라이싱 데이터 추출 [:2, 1:, :]:\n", array3[:2, 1:, :])  

배열 차원 : 3
배열 크기 : (2, 2, 4)
배열 원소 크기 : 4
배열 원소 개수 : 16
배열 내 데이터 타입 : int32
데이터 타입 변경 int32 -> float32
배열 내 데이터 타입 : int32
<class 'numpy.ndarray'>
[[[ 1  3  5  7]
  [ 2  4  6  8]]

 [[11 13 15 17]
  [12 14 16 18]]]
axis0 :
[[12 16 20 24]
 [14 18 22 26]]
axis1 :
[[ 3  7 11 15]
 [23 27 31 35]]
axis2 :
[[16 20]
 [56 60]]
array3 전체 합 : 152
슬라이싱 데이터 추출 [0:2, 0:2, 0:2]:
 [[[ 1  3]
  [ 2  4]]

 [[11 13]
  [12 14]]]
슬라이싱 데이터 추출 [0:2, : , 0:2]:
 [[[ 1  3]
  [ 2  4]]

 [[11 13]
  [12 14]]]
슬라이싱 데이터 추출 [:, 0:1, :]:
 [[[ 1  3  5  7]]

 [[11 13 15 17]]]
슬라이싱 데이터 추출 [:, :, :]:
 [[[ 1  3  5  7]
  [ 2  4  6  8]]

 [[11 13 15 17]
  [12 14 16 18]]]
슬라이싱 데이터 추출 [:2, 1:, :]:
 [[[ 2  4  6  8]]

 [[12 14 16 18]]]


In [58]:
#1차원을 2차원 배열로
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("array1 배열 차원 :", array1.ndim)
array2 = array1.reshape(2,6)
print("array2 배열 차원 :", array2.ndim)
print(type(array2), array2, sep='\n')

#1차원을 3차원 배열로
array3 = array1.reshape(2,2,3)
print("array3 배열 차원 :", array3.ndim)
print(type(array3), array3, sep='\n')

#3차원을 1차원 배열로
array1 = array3.reshape(-1,)
print("array1 배열 차원 :", array1.ndim)
print(type(array1), array1, sep='\n')

array1 배열 차원 : 1
array2 배열 차원 : 2
<class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
array3 배열 차원 : 3
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
array1 배열 차원 : 1
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [80]:
#1차원 배열 정렬, 오름차순, 내림차순
array1 = np.array([1,11,7,4,5,9,3,8,6,12,2,10])

descending = np.sort(array1)
print("오름차순 :", descending)
ascending = np.sort(array1)[::-1]  
print("내림차순 :", ascending)

오름차순 : [ 1  2  3  4  5  6  7  8  9 10 11 12]
내림차순 : [12 11 10  9  8  7  6  5  4  3  2  1]


In [81]:
#1차원 배열 정렬, 오름차순 인덱스, 내림차순 인덱스

descendingIndex = np.argsort(array1)
print("오름차순 Index :", descendingIndex)
print("오름차순 :", array1[descendingIndex])
ascendingIndex = np.argsort(array1)[::-1]  
print("내림차순 Index :", ascendingIndex)
print("내림차순 :", array1[ascendingIndex])

오름차순 Index : [ 0 10  6  3  4  8  2  7  5 11  1  9]
오름차순 : [ 1  2  3  4  5  6  7  8  9 10 11 12]
내림차순 Index : [ 9  1 11  5  7  2  8  4  3  6 10  0]
내림차순 : [12 11 10  9  8  7  6  5  4  3  2  1]


In [98]:
#2차원 배열 정렬, axis 기준 정렬
array2 = np.array([[8,6,2,5],[3,7,1,11]])  
print(array2)
axis1array2 = np.sort(array2, axis=0)
print("axis=0 :", axis1array2, sep='\n')
axis2array2 = np.sort(array2, axis=1)
print("axis=1 :", axis2array2, sep='\n')

[[ 8  6  2  5]
 [ 3  7  1 11]]
axis=0 :
[[ 3  6  1  5]
 [ 8  7  2 11]]
axis=1 :
[[ 2  5  6  8]
 [ 1  3  7 11]]
